### ISSUE TITLE
Add Contact Section

### ISSUE THREAD

**Issue by Riya14-dangra** [Riya14-dangra/RealEstate-Web#1]
An awesome Contact Us page finds just the right balance between making it easy to reach the company and sharing resources users can use to answer their question right away. So make a contact Us page for the website so that user can easily reach to the company owner contact them via email ,contact number ,address and many other  attributes such as other social media platform links e.g Facebook, Instagram , twitter, etc .Design the contact Us page with all this features and make attractive UI for it.

**Comment by harsitagarwalla187** [comment]
Can i work in this issue under KWOC22

**Comment by YadnikaDabhade** [comment]
Hey will you please assign this task to me..
I want to work on it

**Comment by Riya14-dangra** [comment]
> Can i work in this issue under KWOC22

Yes @harsitagarwalla187 go for it.

**Comment by harsitagarwalla187** [comment]
![Screenshot 2022-12-11 224329](https://user-images.githubusercontent.com/84774840/206918246-c737a737-f52f-40f7-be36-2ae650b40a3c.png)
How is it?

**Comment by Riya14-dangra** [comment]
> ![Screenshot 2022-12-11 224329](https://user-images.githubusercontent.com/84774840/206918246-c737a737-f52f-40f7-be36-2ae650b40a3c.png) How is it?

Great LGTM✨

**Comment by SomilRathore01** [comment]
Hey @Riya14-dangra can you please assign this project to me for competing in KWOC 2022.
