### ISSUE TITLE
make Ui design look better(for dark mode) 

### ISSUE THREAD

**Issue by Shubham185y** [Riya14-dangra/RealEstate-Web#10]
i want to work on this i think i can do it very well so please assign this to me

**Comment by Riya14-dangra** [comment]
> i want to work on this i think i can do it very well so please assign this to me

yes go for it

**Comment by Shubham185y** [comment]
https://shubham185y.github.io/RealEstate-Web/#home 
here is the updated version please merge it and let me know if any changes need to make

**Comment by Shubham185y** [comment]
Thank you

**Comment by Shubham185y** [comment]
#13 Merged Thank you
