### ISSUE TITLE
Update ReadMe file

### ISSUE THREAD

**Issue by Riya14-dangra** [Riya14-dangra/RealEstate-Web#4]
Update the readme file and make a pull request to master branch

**Comment by SattyamSamania** [comment]
Hey @Riya14-dangra  Can I work on this if the issue is not solved?

**Comment by harsitagarwalla187** [comment]
I think nobody is working in this issue.
I have updated the website screenshot and also added contributor images.
The changes has been shown below.

![readme](https://user-images.githubusercontent.com/84774840/211022669-5bb857db-398f-44f6-a69a-be5cdf118d72.png)

**Comment by Riya14-dangra** [comment]
Go for it
