### ISSUE TITLE
Add a favicon and preloader to the website

### ISSUE THREAD

**Issue by Janhvi52** [Riya14-dangra/RealEstate-Web#7]
a favicon as a representation of the website and a preloader (preloader in case if you'll someday deploy your page and it'll have a huge loading time then some preloader should be there to show the viewers while the page loads right?)

**Comment by Riya14-dangra** [comment]
@Janhvi52 describe the issue first

**Comment by Janhvi52** [comment]
> @Janhvi52 describe the issue first

You can go though it now

**Comment by Riya14-dangra** [comment]
> > @Janhvi52 describe the issue first
> 
> You can go though it now

@Janhvi52 short the issue tittle and describe the issue in description
